name: Either CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'version.sh'
#  pull_request:
#    paths-ignore:
#      - '**.md'
#      - '.gitignore'
#      - 'version.sh'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build
        id: build
        run: ./gradlew assemble --no-daemon
      - name: Javadoc
        id: javadoc
        if: success()
        run: ./gradlew javadoc --no-daemon
      - name: Test
        id: test
        if: success()
        run: ./gradlew check --no-daemon
      - name: Publish Javadoc
        id: pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: docs
          folder: lib/build/docs/javadoc
          single-commit: true